//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanama.SanamaService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class InternalServerException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class report : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accCodeField;
        
        private string accountNumberField;
        
        private int annualAdjustmentsSubjectField;
        
        private bool annualAdjustmentsSubjectFieldSpecified;
        
        private int assuranceSubjectField;
        
        private bool assuranceSubjectFieldSpecified;
        
        private int assuranceTypeField;
        
        private bool assuranceTypeFieldSpecified;
        
        private int awardArticleField;
        
        private bool awardArticleFieldSpecified;
        
        private int constructArticleField;
        
        private bool constructArticleFieldSpecified;
        
        private string contractPropertiesField;
        
        private string costCenterField;
        
        private string creditCodeField;
        
        private int creditInfoField;
        
        private bool creditInfoFieldSpecified;
        
        private int creditTypeField;
        
        private bool creditTypeFieldSpecified;
        
        private int currencyTypeField;
        
        private bool currencyTypeFieldSpecified;
        
        private string debentureReceiverRankField;
        
        private string debentureSenderRankField;
        
        private int debitSubjectField;
        
        private bool debitSubjectFieldSpecified;
        
        private int demandStatusField;
        
        private bool demandStatusFieldSpecified;
        
        private string dueDateField;
        
        private int expenseArticleField;
        
        private bool expenseArticleFieldSpecified;
        
        private string expenseDetailArticleField;
        
        private int fixedAssetTypeField;
        
        private bool fixedAssetTypeFieldSpecified;
        
        private int governmentalField;
        
        private bool governmentalFieldSpecified;
        
        private int guaranteeEssenceField;
        
        private bool guaranteeEssenceFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string incomeCodeField;
        
        private int incomeSubjectField;
        
        private bool incomeSubjectFieldSpecified;
        
        private int inventoryTypeField;
        
        private bool inventoryTypeFieldSpecified;
        
        private int investmentTypeField;
        
        private bool investmentTypeFieldSpecified;
        
        private int leakageSubjectField;
        
        private bool leakageSubjectFieldSpecified;
        
        private string nomineeField;
        
        private string nomineeCodeField;
        
        private int otherSourceTypeField;
        
        private bool otherSourceTypeFieldSpecified;
        
        private int quantityField;
        
        private bool quantityFieldSpecified;
        
        private string rankNumberField;
        
        private string securitiesPropertiesField;
        
        private int securitiesTypeField;
        
        private bool securitiesTypeFieldSpecified;
        
        private int sourceEssenceField;
        
        private bool sourceEssenceFieldSpecified;
        
        private int sourceTypeField;
        
        private bool sourceTypeFieldSpecified;
        
        private long summaryProgressCreditorField;
        
        private bool summaryProgressCreditorFieldSpecified;
        
        private long summaryProgressDeptorField;
        
        private bool summaryProgressDeptorFieldSpecified;
        
        private int taxSeasonField;
        
        private bool taxSeasonFieldSpecified;
        
        private int tempPaymentTypeField;
        
        private bool tempPaymentTypeFieldSpecified;
        
        private int transferItemsField;
        
        private bool transferItemsFieldSpecified;
        
        private int transferalTypeField;
        
        private bool transferalTypeFieldSpecified;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accCode {
            get {
                return this.accCodeField;
            }
            set {
                this.accCodeField = value;
                this.RaisePropertyChanged("accCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int annualAdjustmentsSubject {
            get {
                return this.annualAdjustmentsSubjectField;
            }
            set {
                this.annualAdjustmentsSubjectField = value;
                this.RaisePropertyChanged("annualAdjustmentsSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool annualAdjustmentsSubjectSpecified {
            get {
                return this.annualAdjustmentsSubjectFieldSpecified;
            }
            set {
                this.annualAdjustmentsSubjectFieldSpecified = value;
                this.RaisePropertyChanged("annualAdjustmentsSubjectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int assuranceSubject {
            get {
                return this.assuranceSubjectField;
            }
            set {
                this.assuranceSubjectField = value;
                this.RaisePropertyChanged("assuranceSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assuranceSubjectSpecified {
            get {
                return this.assuranceSubjectFieldSpecified;
            }
            set {
                this.assuranceSubjectFieldSpecified = value;
                this.RaisePropertyChanged("assuranceSubjectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int assuranceType {
            get {
                return this.assuranceTypeField;
            }
            set {
                this.assuranceTypeField = value;
                this.RaisePropertyChanged("assuranceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool assuranceTypeSpecified {
            get {
                return this.assuranceTypeFieldSpecified;
            }
            set {
                this.assuranceTypeFieldSpecified = value;
                this.RaisePropertyChanged("assuranceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int awardArticle {
            get {
                return this.awardArticleField;
            }
            set {
                this.awardArticleField = value;
                this.RaisePropertyChanged("awardArticle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool awardArticleSpecified {
            get {
                return this.awardArticleFieldSpecified;
            }
            set {
                this.awardArticleFieldSpecified = value;
                this.RaisePropertyChanged("awardArticleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int constructArticle {
            get {
                return this.constructArticleField;
            }
            set {
                this.constructArticleField = value;
                this.RaisePropertyChanged("constructArticle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool constructArticleSpecified {
            get {
                return this.constructArticleFieldSpecified;
            }
            set {
                this.constructArticleFieldSpecified = value;
                this.RaisePropertyChanged("constructArticleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string contractProperties {
            get {
                return this.contractPropertiesField;
            }
            set {
                this.contractPropertiesField = value;
                this.RaisePropertyChanged("contractProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string costCenter {
            get {
                return this.costCenterField;
            }
            set {
                this.costCenterField = value;
                this.RaisePropertyChanged("costCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string creditCode {
            get {
                return this.creditCodeField;
            }
            set {
                this.creditCodeField = value;
                this.RaisePropertyChanged("creditCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int creditInfo {
            get {
                return this.creditInfoField;
            }
            set {
                this.creditInfoField = value;
                this.RaisePropertyChanged("creditInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditInfoSpecified {
            get {
                return this.creditInfoFieldSpecified;
            }
            set {
                this.creditInfoFieldSpecified = value;
                this.RaisePropertyChanged("creditInfoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int creditType {
            get {
                return this.creditTypeField;
            }
            set {
                this.creditTypeField = value;
                this.RaisePropertyChanged("creditType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditTypeSpecified {
            get {
                return this.creditTypeFieldSpecified;
            }
            set {
                this.creditTypeFieldSpecified = value;
                this.RaisePropertyChanged("creditTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int currencyType {
            get {
                return this.currencyTypeField;
            }
            set {
                this.currencyTypeField = value;
                this.RaisePropertyChanged("currencyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencyTypeSpecified {
            get {
                return this.currencyTypeFieldSpecified;
            }
            set {
                this.currencyTypeFieldSpecified = value;
                this.RaisePropertyChanged("currencyTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string debentureReceiverRank {
            get {
                return this.debentureReceiverRankField;
            }
            set {
                this.debentureReceiverRankField = value;
                this.RaisePropertyChanged("debentureReceiverRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string debentureSenderRank {
            get {
                return this.debentureSenderRankField;
            }
            set {
                this.debentureSenderRankField = value;
                this.RaisePropertyChanged("debentureSenderRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int debitSubject {
            get {
                return this.debitSubjectField;
            }
            set {
                this.debitSubjectField = value;
                this.RaisePropertyChanged("debitSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool debitSubjectSpecified {
            get {
                return this.debitSubjectFieldSpecified;
            }
            set {
                this.debitSubjectFieldSpecified = value;
                this.RaisePropertyChanged("debitSubjectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int demandStatus {
            get {
                return this.demandStatusField;
            }
            set {
                this.demandStatusField = value;
                this.RaisePropertyChanged("demandStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool demandStatusSpecified {
            get {
                return this.demandStatusFieldSpecified;
            }
            set {
                this.demandStatusFieldSpecified = value;
                this.RaisePropertyChanged("demandStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("dueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int expenseArticle {
            get {
                return this.expenseArticleField;
            }
            set {
                this.expenseArticleField = value;
                this.RaisePropertyChanged("expenseArticle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expenseArticleSpecified {
            get {
                return this.expenseArticleFieldSpecified;
            }
            set {
                this.expenseArticleFieldSpecified = value;
                this.RaisePropertyChanged("expenseArticleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string expenseDetailArticle {
            get {
                return this.expenseDetailArticleField;
            }
            set {
                this.expenseDetailArticleField = value;
                this.RaisePropertyChanged("expenseDetailArticle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int fixedAssetType {
            get {
                return this.fixedAssetTypeField;
            }
            set {
                this.fixedAssetTypeField = value;
                this.RaisePropertyChanged("fixedAssetType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fixedAssetTypeSpecified {
            get {
                return this.fixedAssetTypeFieldSpecified;
            }
            set {
                this.fixedAssetTypeFieldSpecified = value;
                this.RaisePropertyChanged("fixedAssetTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int governmental {
            get {
                return this.governmentalField;
            }
            set {
                this.governmentalField = value;
                this.RaisePropertyChanged("governmental");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool governmentalSpecified {
            get {
                return this.governmentalFieldSpecified;
            }
            set {
                this.governmentalFieldSpecified = value;
                this.RaisePropertyChanged("governmentalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int guaranteeEssence {
            get {
                return this.guaranteeEssenceField;
            }
            set {
                this.guaranteeEssenceField = value;
                this.RaisePropertyChanged("guaranteeEssence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool guaranteeEssenceSpecified {
            get {
                return this.guaranteeEssenceFieldSpecified;
            }
            set {
                this.guaranteeEssenceFieldSpecified = value;
                this.RaisePropertyChanged("guaranteeEssenceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string incomeCode {
            get {
                return this.incomeCodeField;
            }
            set {
                this.incomeCodeField = value;
                this.RaisePropertyChanged("incomeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int incomeSubject {
            get {
                return this.incomeSubjectField;
            }
            set {
                this.incomeSubjectField = value;
                this.RaisePropertyChanged("incomeSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool incomeSubjectSpecified {
            get {
                return this.incomeSubjectFieldSpecified;
            }
            set {
                this.incomeSubjectFieldSpecified = value;
                this.RaisePropertyChanged("incomeSubjectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public int inventoryType {
            get {
                return this.inventoryTypeField;
            }
            set {
                this.inventoryTypeField = value;
                this.RaisePropertyChanged("inventoryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inventoryTypeSpecified {
            get {
                return this.inventoryTypeFieldSpecified;
            }
            set {
                this.inventoryTypeFieldSpecified = value;
                this.RaisePropertyChanged("inventoryTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public int investmentType {
            get {
                return this.investmentTypeField;
            }
            set {
                this.investmentTypeField = value;
                this.RaisePropertyChanged("investmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool investmentTypeSpecified {
            get {
                return this.investmentTypeFieldSpecified;
            }
            set {
                this.investmentTypeFieldSpecified = value;
                this.RaisePropertyChanged("investmentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public int leakageSubject {
            get {
                return this.leakageSubjectField;
            }
            set {
                this.leakageSubjectField = value;
                this.RaisePropertyChanged("leakageSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leakageSubjectSpecified {
            get {
                return this.leakageSubjectFieldSpecified;
            }
            set {
                this.leakageSubjectFieldSpecified = value;
                this.RaisePropertyChanged("leakageSubjectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string nominee {
            get {
                return this.nomineeField;
            }
            set {
                this.nomineeField = value;
                this.RaisePropertyChanged("nominee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string nomineeCode {
            get {
                return this.nomineeCodeField;
            }
            set {
                this.nomineeCodeField = value;
                this.RaisePropertyChanged("nomineeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public int otherSourceType {
            get {
                return this.otherSourceTypeField;
            }
            set {
                this.otherSourceTypeField = value;
                this.RaisePropertyChanged("otherSourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool otherSourceTypeSpecified {
            get {
                return this.otherSourceTypeFieldSpecified;
            }
            set {
                this.otherSourceTypeFieldSpecified = value;
                this.RaisePropertyChanged("otherSourceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
                this.RaisePropertyChanged("quantitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string rankNumber {
            get {
                return this.rankNumberField;
            }
            set {
                this.rankNumberField = value;
                this.RaisePropertyChanged("rankNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string securitiesProperties {
            get {
                return this.securitiesPropertiesField;
            }
            set {
                this.securitiesPropertiesField = value;
                this.RaisePropertyChanged("securitiesProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public int securitiesType {
            get {
                return this.securitiesTypeField;
            }
            set {
                this.securitiesTypeField = value;
                this.RaisePropertyChanged("securitiesType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool securitiesTypeSpecified {
            get {
                return this.securitiesTypeFieldSpecified;
            }
            set {
                this.securitiesTypeFieldSpecified = value;
                this.RaisePropertyChanged("securitiesTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public int sourceEssence {
            get {
                return this.sourceEssenceField;
            }
            set {
                this.sourceEssenceField = value;
                this.RaisePropertyChanged("sourceEssence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sourceEssenceSpecified {
            get {
                return this.sourceEssenceFieldSpecified;
            }
            set {
                this.sourceEssenceFieldSpecified = value;
                this.RaisePropertyChanged("sourceEssenceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public int sourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("sourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sourceTypeSpecified {
            get {
                return this.sourceTypeFieldSpecified;
            }
            set {
                this.sourceTypeFieldSpecified = value;
                this.RaisePropertyChanged("sourceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public long summaryProgressCreditor {
            get {
                return this.summaryProgressCreditorField;
            }
            set {
                this.summaryProgressCreditorField = value;
                this.RaisePropertyChanged("summaryProgressCreditor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool summaryProgressCreditorSpecified {
            get {
                return this.summaryProgressCreditorFieldSpecified;
            }
            set {
                this.summaryProgressCreditorFieldSpecified = value;
                this.RaisePropertyChanged("summaryProgressCreditorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public long summaryProgressDeptor {
            get {
                return this.summaryProgressDeptorField;
            }
            set {
                this.summaryProgressDeptorField = value;
                this.RaisePropertyChanged("summaryProgressDeptor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool summaryProgressDeptorSpecified {
            get {
                return this.summaryProgressDeptorFieldSpecified;
            }
            set {
                this.summaryProgressDeptorFieldSpecified = value;
                this.RaisePropertyChanged("summaryProgressDeptorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public int taxSeason {
            get {
                return this.taxSeasonField;
            }
            set {
                this.taxSeasonField = value;
                this.RaisePropertyChanged("taxSeason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxSeasonSpecified {
            get {
                return this.taxSeasonFieldSpecified;
            }
            set {
                this.taxSeasonFieldSpecified = value;
                this.RaisePropertyChanged("taxSeasonSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public int tempPaymentType {
            get {
                return this.tempPaymentTypeField;
            }
            set {
                this.tempPaymentTypeField = value;
                this.RaisePropertyChanged("tempPaymentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tempPaymentTypeSpecified {
            get {
                return this.tempPaymentTypeFieldSpecified;
            }
            set {
                this.tempPaymentTypeFieldSpecified = value;
                this.RaisePropertyChanged("tempPaymentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public int transferItems {
            get {
                return this.transferItemsField;
            }
            set {
                this.transferItemsField = value;
                this.RaisePropertyChanged("transferItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferItemsSpecified {
            get {
                return this.transferItemsFieldSpecified;
            }
            set {
                this.transferItemsFieldSpecified = value;
                this.RaisePropertyChanged("transferItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public int transferalType {
            get {
                return this.transferalTypeField;
            }
            set {
                this.transferalTypeField = value;
                this.RaisePropertyChanged("transferalType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferalTypeSpecified {
            get {
                return this.transferalTypeFieldSpecified;
            }
            set {
                this.transferalTypeFieldSpecified = value;
                this.RaisePropertyChanged("transferalTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string checkNoField;
        
        private string dateField;
        
        private string descriptionField;
        
        private string docDateField;
        
        private string docNoField;
        
        private long expenseField;
        
        private bool expenseFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string zinafField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string checkNo {
            get {
                return this.checkNoField;
            }
            set {
                this.checkNoField = value;
                this.RaisePropertyChanged("checkNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
                this.RaisePropertyChanged("docDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string docNo {
            get {
                return this.docNoField;
            }
            set {
                this.docNoField = value;
                this.RaisePropertyChanged("docNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long expense {
            get {
                return this.expenseField;
            }
            set {
                this.expenseField = value;
                this.RaisePropertyChanged("expense");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expenseSpecified {
            get {
                return this.expenseFieldSpecified;
            }
            set {
                this.expenseFieldSpecified = value;
                this.RaisePropertyChanged("expenseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string zinaf {
            get {
                return this.zinafField;
            }
            set {
                this.zinafField = value;
                this.RaisePropertyChanged("zinaf");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class diffType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attachment[] attachmentsField;
        
        private detail[] detailsField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public detail[] details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("valueSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] attachment1Field;
        
        private int attachmentTypeField;
        
        private bool attachmentTypeFieldSpecified;
        
        private string descriptionField;
        
        private string extensionField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] attachment1 {
            get {
                return this.attachment1Field;
            }
            set {
                this.attachment1Field = value;
                this.RaisePropertyChanged("attachment1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int attachmentType {
            get {
                return this.attachmentTypeField;
            }
            set {
                this.attachmentTypeField = value;
                this.RaisePropertyChanged("attachmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentTypeSpecified {
            get {
                return this.attachmentTypeFieldSpecified;
            }
            set {
                this.attachmentTypeFieldSpecified = value;
                this.RaisePropertyChanged("attachmentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class accountNumberImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attachment[] attachmentsField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class contrastAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountDscpField;
        
        private string accountNumberField;
        
        private accountNumberImage accountNumberImageField;
        
        private int accountTypeField;
        
        private bool accountTypeFieldSpecified;
        
        private diffType diffType1Field;
        
        private diffType diffType10Field;
        
        private diffType diffType11Field;
        
        private diffType diffType12Field;
        
        private diffType diffType2Field;
        
        private diffType diffType3Field;
        
        private diffType diffType4Field;
        
        private diffType diffType5Field;
        
        private diffType diffType6Field;
        
        private diffType diffType7Field;
        
        private diffType diffType8Field;
        
        private diffType diffType9Field;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long mojoodiTebgheBankField;
        
        private bool mojoodiTebgheBankFieldSpecified;
        
        private long mojoodiTebgheDaftarField;
        
        private bool mojoodiTebgheDaftarFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountDscp {
            get {
                return this.accountDscpField;
            }
            set {
                this.accountDscpField = value;
                this.RaisePropertyChanged("accountDscp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public accountNumberImage accountNumberImage {
            get {
                return this.accountNumberImageField;
            }
            set {
                this.accountNumberImageField = value;
                this.RaisePropertyChanged("accountNumberImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("accountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountTypeSpecified {
            get {
                return this.accountTypeFieldSpecified;
            }
            set {
                this.accountTypeFieldSpecified = value;
                this.RaisePropertyChanged("accountTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public diffType diffType1 {
            get {
                return this.diffType1Field;
            }
            set {
                this.diffType1Field = value;
                this.RaisePropertyChanged("diffType1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public diffType diffType10 {
            get {
                return this.diffType10Field;
            }
            set {
                this.diffType10Field = value;
                this.RaisePropertyChanged("diffType10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public diffType diffType11 {
            get {
                return this.diffType11Field;
            }
            set {
                this.diffType11Field = value;
                this.RaisePropertyChanged("diffType11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public diffType diffType12 {
            get {
                return this.diffType12Field;
            }
            set {
                this.diffType12Field = value;
                this.RaisePropertyChanged("diffType12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public diffType diffType2 {
            get {
                return this.diffType2Field;
            }
            set {
                this.diffType2Field = value;
                this.RaisePropertyChanged("diffType2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public diffType diffType3 {
            get {
                return this.diffType3Field;
            }
            set {
                this.diffType3Field = value;
                this.RaisePropertyChanged("diffType3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public diffType diffType4 {
            get {
                return this.diffType4Field;
            }
            set {
                this.diffType4Field = value;
                this.RaisePropertyChanged("diffType4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public diffType diffType5 {
            get {
                return this.diffType5Field;
            }
            set {
                this.diffType5Field = value;
                this.RaisePropertyChanged("diffType5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public diffType diffType6 {
            get {
                return this.diffType6Field;
            }
            set {
                this.diffType6Field = value;
                this.RaisePropertyChanged("diffType6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public diffType diffType7 {
            get {
                return this.diffType7Field;
            }
            set {
                this.diffType7Field = value;
                this.RaisePropertyChanged("diffType7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public diffType diffType8 {
            get {
                return this.diffType8Field;
            }
            set {
                this.diffType8Field = value;
                this.RaisePropertyChanged("diffType8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public diffType diffType9 {
            get {
                return this.diffType9Field;
            }
            set {
                this.diffType9Field = value;
                this.RaisePropertyChanged("diffType9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public long mojoodiTebgheBank {
            get {
                return this.mojoodiTebgheBankField;
            }
            set {
                this.mojoodiTebgheBankField = value;
                this.RaisePropertyChanged("mojoodiTebgheBank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mojoodiTebgheBankSpecified {
            get {
                return this.mojoodiTebgheBankFieldSpecified;
            }
            set {
                this.mojoodiTebgheBankFieldSpecified = value;
                this.RaisePropertyChanged("mojoodiTebgheBankSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public long mojoodiTebgheDaftar {
            get {
                return this.mojoodiTebgheDaftarField;
            }
            set {
                this.mojoodiTebgheDaftarField = value;
                this.RaisePropertyChanged("mojoodiTebgheDaftar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mojoodiTebgheDaftarSpecified {
            get {
                return this.mojoodiTebgheDaftarFieldSpecified;
            }
            set {
                this.mojoodiTebgheDaftarFieldSpecified = value;
                this.RaisePropertyChanged("mojoodiTebgheDaftarSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/")]
    public partial class sanamaInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attachment[] attachmentsField;
        
        private contrastAccount[] contrastAccountsField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string mainOrgCodeField;
        
        private string mainOrgIDField;
        
        private int monthField;
        
        private bool monthFieldSpecified;
        
        private string protocolNameField;
        
        private string protocolTypeField;
        
        private string protocolVerField;
        
        private report[] reportsField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contrastAccounts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public contrastAccount[] contrastAccounts {
            get {
                return this.contrastAccountsField;
            }
            set {
                this.contrastAccountsField = value;
                this.RaisePropertyChanged("contrastAccounts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mainOrgCode {
            get {
                return this.mainOrgCodeField;
            }
            set {
                this.mainOrgCodeField = value;
                this.RaisePropertyChanged("mainOrgCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mainOrgID {
            get {
                return this.mainOrgIDField;
            }
            set {
                this.mainOrgIDField = value;
                this.RaisePropertyChanged("mainOrgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthSpecified {
            get {
                return this.monthFieldSpecified;
            }
            set {
                this.monthFieldSpecified = value;
                this.RaisePropertyChanged("monthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string protocolName {
            get {
                return this.protocolNameField;
            }
            set {
                this.protocolNameField = value;
                this.RaisePropertyChanged("protocolName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string protocolType {
            get {
                return this.protocolTypeField;
            }
            set {
                this.protocolTypeField = value;
                this.RaisePropertyChanged("protocolType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string protocolVer {
            get {
                return this.protocolVerField;
            }
            set {
                this.protocolVerField = value;
                this.RaisePropertyChanged("protocolVer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reports", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public report[] reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
                this.RaisePropertyChanged("reports");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/", ConfigurationName="SanamaService.PushSanama")]
    public interface PushSanama {
        
        // CODEGEN: Parameter 'responseMessage' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sanama.SanamaService.InternalServerException), Action="", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Name="InternalServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responseMessage")]
        Sanama.SanamaService.sendResponse send(Sanama.SanamaService.send request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Sanama.SanamaService.sendResponse> sendAsync(Sanama.SanamaService.send request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/", IsWrapped=true)]
    public partial class send {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sanama.SanamaService.sanamaInfo sanamaInfo;
        
        public send() {
        }
        
        public send(Sanama.SanamaService.sanamaInfo sanamaInfo) {
            this.sanamaInfo = sanamaInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/", IsWrapped=true)]
    public partial class sendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicebus.sanama.mefa.ir/PushSanama/v1/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responseMessage;
        
        public sendResponse() {
        }
        
        public sendResponse(string responseMessage) {
            this.responseMessage = responseMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PushSanamaChannel : Sanama.SanamaService.PushSanama, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushSanamaClient : System.ServiceModel.ClientBase<Sanama.SanamaService.PushSanama>, Sanama.SanamaService.PushSanama {
        
        public PushSanamaClient() {
        }
        
        public PushSanamaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushSanamaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushSanamaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushSanamaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sanama.SanamaService.sendResponse Sanama.SanamaService.PushSanama.send(Sanama.SanamaService.send request) {
            return base.Channel.send(request);
        }
        
        public string send(Sanama.SanamaService.sanamaInfo sanamaInfo) {
            Sanama.SanamaService.send inValue = new Sanama.SanamaService.send();
            inValue.sanamaInfo = sanamaInfo;
            Sanama.SanamaService.sendResponse retVal = ((Sanama.SanamaService.PushSanama)(this)).send(inValue);
            return retVal.responseMessage;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sanama.SanamaService.sendResponse> Sanama.SanamaService.PushSanama.sendAsync(Sanama.SanamaService.send request) {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sanama.SanamaService.sendResponse> sendAsync(Sanama.SanamaService.sanamaInfo sanamaInfo) {
            Sanama.SanamaService.send inValue = new Sanama.SanamaService.send();
            inValue.sanamaInfo = sanamaInfo;
            return ((Sanama.SanamaService.PushSanama)(this)).sendAsync(inValue);
        }
    }
}
